package traversium.notification.mapper

/**
 * @author Maja Razinger
 */
enum class NotificationType {
    ADD_COMMENT,
    REPLY_COMMENT,
    LIKE_PHOTO,
    CREATE_MOMENT,
    REARRANGE_MOMENTS,
    CHANGE_MOMENT_COVER_PHOTO,
    CHANGE_MOMENT_TITLE,
    CHANGE_MOMENT_DESCRIPTION,
    DELETE_MOMENT,
    ADD_PHOTO,
    REMOVE_PHOTO,
    CREATE_TRIP,
    DELETE_TRIP,
    CHANGE_TRIP_TITLE,
    CHANGE_TRIP_DESCRIPTION,
    CHANGE_TRIP_COVER_PHOTO,
    ADD_COLLABORATOR,
    ADD_VIEWER,
    REMOVE_COLLABORATOR,
    REMOVE_VIEWER,
    HEALTHCHECK,
    FOLLOW_USER,
    UNKNOWN
}